// Diatonic scales with triad and 7th chord qualities on each degree.
// Each degree: { semi, triad: [typeId, roman], seventh: [typeId, roman] }

export const SCALES = [
  {
    id: 'major',
    name: 'Major',
    group: 'primary',
    degrees: [
      { semi: 0,  triad: ['maj', 'I'],    seventh: ['maj7', 'Imaj7'] },
      { semi: 2,  triad: ['min', 'ii'],   seventh: ['min7', 'ii7'] },
      { semi: 4,  triad: ['min', 'iii'],  seventh: ['min7', 'iii7'] },
      { semi: 5,  triad: ['maj', 'IV'],   seventh: ['maj7', 'IVmaj7'] },
      { semi: 7,  triad: ['maj', 'V'],    seventh: ['dom7', 'V7'] },
      { semi: 9,  triad: ['min', 'vi'],   seventh: ['min7', 'vi7'] },
      { semi: 11, triad: ['dim', 'vii°'], seventh: ['m7b5', 'viiø7'] },
    ],
  },
  {
    id: 'minor',
    name: 'Minor',
    group: 'primary',
    degrees: [
      { semi: 0,  triad: ['min', 'i'],    seventh: ['min7', 'i7'] },
      { semi: 2,  triad: ['dim', 'ii°'],  seventh: ['m7b5', 'iiø7'] },
      { semi: 3,  triad: ['maj', '♭III'], seventh: ['maj7', '♭IIImaj7'] },
      { semi: 5,  triad: ['min', 'iv'],   seventh: ['min7', 'iv7'] },
      { semi: 7,  triad: ['min', 'v'],    seventh: ['min7', 'v7'] },
      { semi: 8,  triad: ['maj', '♭VI'],  seventh: ['maj7', '♭VImaj7'] },
      { semi: 10, triad: ['maj', '♭VII'], seventh: ['dom7', '♭VII7'] },
    ],
  },
  {
    id: 'harmonic-minor',
    name: 'Harmonic Minor',
    degrees: [
      { semi: 0,  triad: ['min',  'i'],     seventh: ['min7', 'i7'] },
      { semi: 2,  triad: ['dim',  'ii°'],   seventh: ['m7b5', 'iiø7'] },
      { semi: 3,  triad: ['aug',  '♭III+'], seventh: ['maj7', '♭IIImaj7'] },
      { semi: 5,  triad: ['min',  'iv'],    seventh: ['min7', 'iv7'] },
      { semi: 7,  triad: ['maj',  'V'],     seventh: ['dom7', 'V7'] },
      { semi: 8,  triad: ['maj',  '♭VI'],   seventh: ['maj7', '♭VImaj7'] },
      { semi: 11, triad: ['dim',  'vii°'],  seventh: ['dim7', 'vii°7'] },
    ],
  },
  {
    id: 'melodic-minor',
    name: 'Melodic Minor',
    degrees: [
      { semi: 0,  triad: ['min', 'i'],     seventh: ['min7',  'i(maj7)'] },
      { semi: 2,  triad: ['min', 'ii'],    seventh: ['min7',  'ii7'] },
      { semi: 3,  triad: ['aug', '♭III+'], seventh: ['maj7',  '♭IIImaj7♯5'] },
      { semi: 5,  triad: ['maj', 'IV'],    seventh: ['dom7',  'IV7'] },
      { semi: 7,  triad: ['maj', 'V'],     seventh: ['dom7',  'V7'] },
      { semi: 9,  triad: ['dim', 'vi°'],   seventh: ['m7b5',  'viø7'] },
      { semi: 11, triad: ['dim', 'vii°'],  seventh: ['m7b5',  'viiø7'] },
    ],
  },
  {
    id: 'dorian',
    name: 'Dorian',
    degrees: [
      { semi: 0,  triad: ['min', 'i'],     seventh: ['min7', 'i7'] },
      { semi: 2,  triad: ['min', 'ii'],    seventh: ['min7', 'ii7'] },
      { semi: 3,  triad: ['maj', '♭III'],  seventh: ['maj7', '♭IIImaj7'] },
      { semi: 5,  triad: ['maj', 'IV'],    seventh: ['dom7', 'IV7'] },
      { semi: 7,  triad: ['min', 'v'],     seventh: ['min7', 'v7'] },
      { semi: 9,  triad: ['dim', 'vi°'],   seventh: ['m7b5', 'viø7'] },
      { semi: 10, triad: ['maj', '♭VII'],  seventh: ['maj7', '♭VIImaj7'] },
    ],
  },
  {
    id: 'phrygian',
    name: 'Phrygian',
    degrees: [
      { semi: 0,  triad: ['min', 'i'],     seventh: ['min7', 'i7'] },
      { semi: 1,  triad: ['maj', '♭II'],   seventh: ['maj7', '♭IImaj7'] },
      { semi: 3,  triad: ['maj', '♭III'],  seventh: ['dom7', '♭III7'] },
      { semi: 5,  triad: ['min', 'iv'],    seventh: ['min7', 'iv7'] },
      { semi: 7,  triad: ['dim', 'v°'],    seventh: ['m7b5', 'vø7'] },
      { semi: 8,  triad: ['maj', '♭VI'],   seventh: ['maj7', '♭VImaj7'] },
      { semi: 10, triad: ['min', '♭vii'],  seventh: ['min7', '♭vii7'] },
    ],
  },
  {
    id: 'lydian',
    name: 'Lydian',
    degrees: [
      { semi: 0,  triad: ['maj', 'I'],     seventh: ['maj7', 'Imaj7'] },
      { semi: 2,  triad: ['maj', 'II'],    seventh: ['dom7', 'II7'] },
      { semi: 4,  triad: ['min', 'iii'],   seventh: ['min7', 'iii7'] },
      { semi: 6,  triad: ['dim', '♯iv°'],  seventh: ['m7b5', '♯ivø7'] },
      { semi: 7,  triad: ['maj', 'V'],     seventh: ['maj7', 'Vmaj7'] },
      { semi: 9,  triad: ['min', 'vi'],    seventh: ['min7', 'vi7'] },
      { semi: 11, triad: ['min', 'vii'],   seventh: ['min7', 'vii7'] },
    ],
  },
  {
    id: 'mixolydian',
    name: 'Mixolydian',
    degrees: [
      { semi: 0,  triad: ['maj', 'I'],     seventh: ['dom7', 'I7'] },
      { semi: 2,  triad: ['min', 'ii'],    seventh: ['min7', 'ii7'] },
      { semi: 4,  triad: ['dim', 'iii°'],  seventh: ['m7b5', 'iiiø7'] },
      { semi: 5,  triad: ['maj', 'IV'],    seventh: ['maj7', 'IVmaj7'] },
      { semi: 7,  triad: ['min', 'v'],     seventh: ['min7', 'v7'] },
      { semi: 9,  triad: ['min', 'vi'],    seventh: ['min7', 'vi7'] },
      { semi: 10, triad: ['maj', '♭VII'],  seventh: ['maj7', '♭VIImaj7'] },
    ],
  },
  {
    id: 'locrian',
    name: 'Locrian',
    degrees: [
      { semi: 0,  triad: ['dim', 'i°'],    seventh: ['m7b5', 'iø7'] },
      { semi: 1,  triad: ['maj', '♭II'],   seventh: ['maj7', '♭IImaj7'] },
      { semi: 3,  triad: ['min', '♭iii'],  seventh: ['min7', '♭iii7'] },
      { semi: 5,  triad: ['min', 'iv'],    seventh: ['min7', 'iv7'] },
      { semi: 6,  triad: ['maj', '♭V'],    seventh: ['maj7', '♭Vmaj7'] },
      { semi: 8,  triad: ['maj', '♭VI'],   seventh: ['dom7', '♭VI7'] },
      { semi: 10, triad: ['min', '♭vii'],  seventh: ['min7', '♭vii7'] },
    ],
  },
  {
    id: 'phrygian-dominant',
    name: 'Phrygian Dominant',
    degrees: [
      { semi: 0,  triad: ['maj', 'I'],     seventh: ['dom7', 'I7'] },
      { semi: 1,  triad: ['maj', '♭II'],   seventh: ['maj7', '♭IImaj7'] },
      { semi: 4,  triad: ['dim', 'iii°'],  seventh: ['dim7', 'iii°7'] },
      { semi: 5,  triad: ['min', 'iv'],    seventh: ['min7', 'iv7'] },
      { semi: 7,  triad: ['dim', 'v°'],    seventh: ['m7b5', 'vø7'] },
      { semi: 8,  triad: ['aug', '♭VI+'],  seventh: ['maj7', '♭VImaj7♯5'] },
      { semi: 10, triad: ['min', '♭vii'],  seventh: ['min7', '♭vii7'] },
    ],
  },
]
